FROM agrigorev/zoomcamp-model:2025

RUN pip install uv

COPY ["pyproject.toml", "uv.lock","./"]
RUN uv sync --locked

COPY ["service.py","./"]

EXPOSE 9696

ENTRYPOINT [ "uv","run","uvicorn", "service:app", "--host", "0.0.0.0", "--port", "9696" ]